#! /usr/bin/env python3

import os, glob, sys, re, math
import numpy as np
import xyzgeom
import pandas as pd
from optparse import OptionParser

def ParseInput(ArgsIn):
   UseMsg = '''
   Usage: python [script] [options] [target_dir] [xyzfile]
   '''
   parser = OptionParser(usage=UseMsg)
   parser.add_option('--placeholder',dest='placeholder',action='store',type='string',default=None,help='keyword for parsing the job index (default: None, which uses the full job name)')
   parser.add_option('--method',dest='method',action='store',type='string',default='scf',
      help='electronic structure method that generates the forces (default: scf; also support: tddft, ccsd, eom-ccsd)')
   parser.add_option('--sol',dest='sol',action='store_true',default=False,help="Turn this on when implicit solvent is used; currently supporting PCM and SMD")

   options, args = parser.parse_args(ArgsIn)
   if len(args) < 3:
      parser.print_help()
      sys.exit(0)
   if options.sol and options.method.lower() != 'scf':
      print ("The --sol option only works for HF/DFT forces right now")
      sys.exit(0)
   #regulate the placeholder: removing "_" at the end
   if options.placeholder != None and options.placeholder[-1] == "_":
      options.placeholder = options.placeholder[:-1]

   return options, args

def parse_forces(infile):
   fr = open(infile, 'r')
   start_parsing = False
   begin = -1
   end = -1
   forces = np.array([])
   forces_temp = None
   N = -1
   counter = -1
   for line in fr.readlines():
      l_sp = line.split()
      if l_sp[0] == 'Full' or l_sp[0] == 'Gradient':
         start_parsing = True
         counter = 0
         continue
      if l_sp[0] == 'Max': #for SCF jobs
         break
      if l_sp[0] == 'Gradient' and counter > 0: #for other methods
         break
      if start_parsing:
         if counter == 0: #atom index line
            begin = int(l_sp[0])
            end = int(l_sp[-1])
            N = end - begin + 1 #number of atoms in this batch
            forces_temp = np.zeros((N, 3))
            counter += 1
         else:
            for idx in range(N):
               forces_temp[idx][counter-1] = float(l_sp[idx+1]) #the first index is line number (1/2/3)
            if counter == 3:
               if len(forces) == 0:
                  forces = forces_temp
               else:
                  forces = np.vstack((forces, forces_temp))
               counter = 0
            else:
               counter += 1
   fr.close()
   return forces

def parse_forces_scf_sol(infile):
   forces = np.array([])
   fr = open(infile, 'r')
   for line in fr.readlines():
      l_sp = line.split()
      if len(l_sp) == 4 and l_sp[0].isnumeric():
         f_i = np.array([float(l_sp[1]), float(l_sp[2]), float(l_sp[3])]) 
         if len(forces) == 0:
            forces = f_i
         else:
            forces = np.vstack((forces, f_i))
   fr.close()
   return forces


def write_forces(grad_file, forces, AtomList):
   fw = open(grad_file, 'w')
   fw.write("%d\n\n" %len(AtomList))
   for i in range(len(AtomList)):
      fw.write("%s %12.10f %12.10f %12.10f\n" %(AtomList[i], forces[i, 0], forces[i, 1], forces[i, 2]))
   fw.close()

def generate_all_forces(AtomList, options):
   outfile_list = glob.glob('*.out')
   for outfile in outfile_list:
      tmpfile = "tmp.txt"
      if options.method.lower() == 'scf': #default
         if options.sol:
            command = "sed -n '/-- total grad/,/Gradient time/p' " + outfile + " > " + tmpfile
         else:
            command = "sed -n '/Gradient of SCF Energy/,/Gradient time/p' " + outfile + " > " + tmpfile
      elif options.method.lower() == 'tddft':
         command = "sed -n '/Gradient of the state energy/,/Gradient time/p' " + outfile + " > " + tmpfile
      elif options.method.lower() == 'ccsd' or options.method.lower() == 'eom-ccsd':
         command = "sed -n '/Full Analytical/,/Gradient time/p' " + outfile + " > " + tmpfile
      else:
         print ("Electronic structure method not supported by this script")
         sys.exit(1)
      os.system(command)
      if options.sol:
         forces = parse_forces_scf_sol(tmpfile)
      else:
         forces = parse_forces(tmpfile)
      #print (forces)
      if forces.shape[0] != len(AtomList):
         print ("Length of AtomList: %d; rows in forces: %d" %(len(AtomList), forces.shape[0])) 
      if options.placeholder != None:
         l = re.search(options.placeholder+'_(\d+)_([^_]+)', outfile)
         job_idx = int(l.group(1))
         if options.method.lower() == 'tddft' or options.method.lower() == 'eom-ccsd':
            grad_type = 'ex'
         else:
            grad_type = 'gs'
         grad_file = 'grad_' + grad_type + "{:03n}".format(job_idx) + '.txt'
      else:  #general mode
         grad_file = outfile[:-4] + '.grad'
      write_forces(grad_file, forces, AtomList)
   os.system('rm '+tmpfile)

options, args = ParseInput(sys.argv)
target_dir = args[1]
xyzfile = args[2] #note: the only use of this xyzfile is to get the atom list
AtomList, Coords = xyzgeom.parse_xyz_file(xyzfile)
print ("%d atoms in total" %len(AtomList))
curdir = os.getcwd()
os.chdir(target_dir)
generate_all_forces(AtomList, options)
os.chdir(curdir)
