#! /usr/bin/env python3

import os, glob, sys, re
import xyzgeom
import numpy as np
from optparse import OptionParser

def ParseInput(ArgsIn):
   UseMsg = "get_angle_w_axis [options] [xyzdir] [bond_atom1] [bond_atom2]"
   parser = OptionParser(usage=UseMsg)
   parser.add_option('--axis',dest='axis',action='store',type='str',default='Z',help='The axis to use (default: Z)')

   options, args = parser.parse_args(ArgsIn)
   if len(args) < 4:
      parser.print_help()
      sys.exit(0)
   return options,args

options, args = ParseInput(sys.argv)
target_dir = args[1] #Now only support doing all files under a directory
atom_idx1, atom_idx2 = int(args[2]), int(args[3])
if target_dir[-1] == "/":
   target_dir = target_dir[:-1]

xyzfile_list = glob.glob(target_dir+'/*.xyz')
data = {}
for xyzfile in xyzfile_list:
   efield = int(re.search('_([^_]+).xyz', xyzfile).group(1))
   AtomList, Coords = xyzgeom.parse_xyz_file(xyzfile)
   angle = xyzgeom.compute_angle_w_axis(Coords, atom_idx1, atom_idx2, options.axis)
   data[efield] = angle

outfile = target_dir+'/angle_'+options.axis.upper()+'.csv'
fw = open(outfile, 'w')
for efield in sorted(data, reverse=True):
   print('%.1f,%.3f' %(efield, data[efield]))
   fw.write('%.1f,%.3f\n' %(efield, data[efield]))
fw.close()
