#! /usr/bin/env python

import os, glob, re, sys
import subprocess as sp
import numpy as np
from optparse import OptionParser
import qrems, qmol

def ParseInput(ArgsIn):
   UseMsg = '''
   make_input_sp_geom [options] [xyz_path]
   '''
   parser = OptionParser(usage=UseMsg)
   parser.add_option('--opt',dest='opt',action='store_true',default=False,help='doing geom opt instead of single-point energy')
   parser.add_option('-a','--all',dest='all',action='store_true',default=False,help='run all the xyz files under the xyz_path')
   parser.add_option('-k','--keyword',dest='keyword',action='store',type='string',default=None,help='create inputs for xyz files containing the keyword')
   parser.add_option('-t','--target',dest='target',action='callback',callback=string_sp_callback,type='string',default=None,help='create input for certain xyz files')
   parser.add_option('-b','--basis',dest='basis',action='callback',callback=string_sp_callback, type='string', default='aug-cc-pvtz',help='The target basis (default is aug-cc-pVTZ)')
   parser.add_option('-m','--method',dest='method',action='callback',type='string', default=None, callback=string_sp_callback,help='The methods (density functionals) to use')
   parser.add_option('-i','--input_path',dest='input_path',action='store',type='string', default='input/',help='The directory storing the generated inputs')
   parser.add_option('--charge',dest='charge',action='store',type='int',default=0,help='total charge of the system')
   parser.add_option('--mult',dest='mult',action='store',type='int',default=1,help='total multiplicity of the system') 
   parser.add_option('--sol',dest='sol',action='store',type='string',default=None,help='specify the solvent model to use')
   parser.add_option('--sol_file', dest='sol_file', action='store', type='string', default=None, help='file for the solvent model input section')

   options, args = parser.parse_args(ArgsIn)
   if len(args) < 2 and (options.all or options.keyword!=None):
      parser.print_help()
      sys.exit(0)
   if not options.all and options.target==None and options.keyword==None:
      print "The target directory must be specified: one or some or all"
      parser.print_help()
      sys.exit(1)
   if options.sol_file != None and options.sol == None:
      print "Solvent method must be specified when sol_file is given"
      sys.exit(0)
   return options, args

def string_sp_callback(option, opt, value, parser):
   setattr(parser.values, option.dest, value.split(','))

def XYZ_to_Input(fw, XYZ, curREM, options):
   qmol.WriteMolecule(fw, XYZ, options.charge, options.mult)
   qrems.AppendRem(fw, curREM)
   if options.sol_file != None:
      if not os.path.exists(options.sol_file):
         print "specified pcm file does not exist"
         sys.exit(0)
      else:
         qrems.copy_section_over(fw, options.sol_file)

options, args = ParseInput(sys.argv)
xyz_path =''
if len(args) > 1:
   xyz_path = args[1]
   if xyz_path[-1:] != '/':
      xyz_path += '/'

#determine xyz_file
curdir = os.getcwd()
xyzfile_list = []
if options.all:
   xyzfile_list = glob.glob(xyz_path+'*.xyz')
elif options.keyword:
   xyzfile_list = glob.glob(xyz_path+'*'+options.keyword+'*.xyz')
if options.target!=None:
   for xyz_file in options.target:
      if xyz_file not in xyzfile_list:
         xyzfile_list.append(xyz_file)

#check the input_path
input_path = options.input_path
if input_path[-1:] != '/':
   input_path += '/'
if not os.path.exists(input_path):
   sp.call(['mkdir', input_path])

rem_file = os.path.expandvars('$QREMPATH')+'/rem_stdscf'
myrems = qrems.ParseRems(rem_file)
if options.opt:
   qrems.ModRem('JOBTYPE', 'OPT', myrems)
if options.sol != None:
   qrems.ModRem('SOLVENT_METHOD', options.sol, myrems)

for method in options.method:
   for basis in options.basis:
      qrems.set_rems_common(myrems, method, basis)
      for xyz_file in xyzfile_list:
         parsed_XYZ = qmol.XYZ(xyz_file)
         if options.opt:
            inputfile = input_path+parsed_XYZ.Name+'_geom_'+method+'_'+qrems.basis_abbr(basis)+'.in' 
         else:
            inputfile = input_path+parsed_XYZ.Name+'_'+method+'_'+qrems.basis_abbr(basis)+'.in' 
         fw = open(inputfile, 'w')
         XYZ_to_Input(fw, parsed_XYZ, myrems, options)
         fw.close()

