#! /usr/bin/env python

import os, glob, re, sys
import subprocess as sp
import numpy as np
from optparse import OptionParser
import qrems, qmol

def ParseInput(ArgsIn):
   UseMsg = '''
   make_input_sp_geom [options] [xyz_path]
   '''
   parser = OptionParser(usage=UseMsg)
   parser.add_option('--opt',dest='opt',action='store_true',default=False,help='doing geom opt instead of single-point energy')
   parser.add_option('-a','--all',dest='all',action='store_true',default=False,help='run all the xyz files under the xyz_path')
   parser.add_option('-k','--keyword',dest='keyword',action='store',type='string',default=None,help='create inputs for xyz files containing the keyword')
   parser.add_option('-t','--target',dest='target',action='callback',callback=string_sp_callback,type='string',default=None,help='create input for certain xyz files')
   parser.add_option('-b','--basis',dest='basis',action='callback',callback=string_sp_callback, type='string', default='aug-cc-pvtz',help='The target basis (default is aug-cc-pVTZ)')
   parser.add_option('-m','--method',dest='method',action='callback',type='string', default=None, callback=string_sp_callback,help='The methods (density functionals) to use')
   parser.add_option('-i','--input_path',dest='input_path',action='store',type='string', default='input/',help='The directory storing the generated inputs')
   parser.add_option('--charge',dest='charge',action='store',type='int',default=0,help='total charge of the system')
   parser.add_option('--mult',dest='mult',action='store',type='int',default=1,help='total multiplicity of the system') 
   parser.add_option('--sol',dest='sol',action='store',type='string',default=None,help='specify the solvent model to use')
   parser.add_option('--sol_file', dest='sol_file', action='store', type='string', default=None, help='file for the solvent model input section')
   parser.add_option('--geom_constr', dest='geom_constr', action='store', default=None, type='string', help='specify the template file for adding geometry optimization constraint')
   parser.add_option('--tight',dest='tight',action='store_true',default=False,help='use tigher criterion for geom opt convergence')
   parser.add_option('--coarse',dest='coarse',action='store_true',default=False,help='use less tight integral thresh and less fine grid for SCF calculations')
   parser.add_option('--sym',dest='sym',action='store_true',default=False,help='use sym_ignore = false for geom opt')
   parser.add_option('--stab',dest='stab',action='store_true',default=False,help='use gdm algorithm and turn on stability analysis')
   parser.add_option('--efield',dest='efield',action='store_true',default=False,help='calculate electric field')
   parser.add_option('--dipole_field',dest='dipole_field',action='store',type='int',default=None,help='apply a dipolar field along Z direction')

   options, args = parser.parse_args(ArgsIn)
   if len(args) < 2 and (options.all or options.keyword!=None):
      parser.print_help()
      sys.exit(0)
   if not options.all and options.target==None and options.keyword==None:
      print("The target directory must be specified: one or some or all")
      parser.print_help()
      sys.exit(1)
   if options.sol_file != None and (not os.path.exists(options.sol_file)):
      print("Specified sol_file does not exist")
      sys.exit(0)
   return options, args

def string_sp_callback(option, opt, value, parser):
   setattr(parser.values, option.dest, value.split(','))

def append_single_geom_constraint(fw, constraint_template, XYZ, placeholder='dist'):
   l = re.search(placeholder+'_(\S+)', XYZ.Name)
   if l == None:
      print("No geom_param specified in xyz file name. Try different placeholder or you are fucked")
      sys.exit(0)
   geom_param = float(l.group(1))
   qrems.apply_single_geom_constraint(fw, geom_param, constraint_template)

def XYZ_to_Input(fw, XYZ, curREM, options):
   qmol.WriteMolecule(fw, XYZ, options.charge, options.mult)
   qrems.AppendRem(fw, curREM)
   if options.geom_constr != None:
      append_single_geom_constraint(fw, options.geom_constr, XYZ, 'bond')
   if options.sol_file != None:
      if not os.path.exists(options.sol_file):
         print("specified pcm file does not exist")
         sys.exit(0)
      else:
         qrems.copy_section_over(fw, options.sol_file)
   if options.dipole_field != None and options.dipole_field != 0:
      append_dipolar_field(fw, options.dipole_field)

def append_dipolar_field(fw, dipole_field):
   field_in_au = -1.0 * float(dipole_field) / 5142.0 #note: the minus comes from q-chem's convention
   fw.write('\n$multipole_field\n')
   fw.write('Z\t%.6f\n' %field_in_au)
   fw.write('$end\n')

def set_tight_opt_criterion(curREM):
   qrems.ModRem('GEOM_OPT_TOL_GRADIENT','100', curREM)
   qrems.ModRem('GEOM_OPT_TOL_DISPLACEMENT', '100', curREM)
   qrems.ModRem('GEOM_OPT_TOL_ENERGY', '10', curREM)

options, args = ParseInput(sys.argv)
xyz_path =''
if len(args) > 1:
   xyz_path = args[1]
   if xyz_path[-1:] != '/':
      xyz_path += '/'

#determine xyz_file
curdir = os.getcwd()
xyzfile_list = []
if options.all:
   xyzfile_list = glob.glob(xyz_path+'*.xyz')
elif options.keyword:
   xyzfile_list = glob.glob(xyz_path+'*'+options.keyword+'*.xyz')
if options.target!=None:
   for xyz_file in options.target:
      if xyz_file not in xyzfile_list:
         xyzfile_list.append(xyz_file)

#check the input_path
input_path = options.input_path
if input_path[-1:] != '/':
   input_path += '/'
if not os.path.exists(input_path):
   sp.call(['mkdir', input_path])

rem_file = os.path.expandvars('$QREMPATH')+'/rem_stdscf'
myrems = qrems.ParseRems(rem_file)
if options.opt:
   qrems.ModRem('JOBTYPE', 'OPT', myrems)
   qrems.ModRem('GEOM_OPT_MAX_CYCLES', '200', myrems)
if options.tight:
   set_tight_opt_criterion(myrems)
if options.sym:
   qrems.ModRem('SYM_IGNORE', 'FALSE', myrems)
if options.sol != None:
   qrems.ModRem('SOLVENT_METHOD', options.sol, myrems)
if options.stab:
   qrems.ModRem('SCF_ALGORITHM', 'GDM', myrems)
   qrems.ModRem('INTERNAL_STABILITY', 'TRUE', myrems)
if options.efield:
   qrems.ModRem('ESP_GRID', '0', myrems)
   qrems.ModRem('ESP_EFIELD', '1', myrems)

for method in options.method:
   for basis in options.basis:
      qrems.set_rems_common(myrems, method, basis, options.coarse)
      for xyz_file in xyzfile_list:
         parsed_XYZ = qmol.XYZ(xyz_file)
         if options.dipole_field != None:
            if options.dipole_field > 0:
               inputfile = input_path+parsed_XYZ.Name+'_+'+str(options.dipole_field)+'.in'
            elif options.dipole_field == 0:
               inputfile = input_path+parsed_XYZ.Name+'_0.in'
            else:
               inputfile = input_path+parsed_XYZ.Name+'_'+str(options.dipole_field)+'.in'
         else:
            if options.opt:
               inputfile = input_path+parsed_XYZ.Name+'_geom_'+method+'_'+qrems.basis_abbr(basis)+'.in'
            else:
               inputfile = input_path+parsed_XYZ.Name+'_'+method+'_'+qrems.basis_abbr(basis)+'.in'
         fw = open(inputfile, 'w')
         XYZ_to_Input(fw, parsed_XYZ, myrems, options)
         fw.close()
