#! /usr/bin/env python3

import os, glob, re, sys
import subprocess as sp
import numpy as np
from optparse import OptionParser

def ParseInput(ArgsIn):
   UseMsg = '''
   python make_input_E_bind.py [options] [xyz_path] [rem_file] [frgm_partition]
   ''' 
   parser = OptionParser(usage=UseMsg)
   parser.add_option('-a','--all',dest='all',action='store_true',default=False,help='run all the xyz files under the xyz_path')
   parser.add_option('-k','--keyword',dest='keyword',action='store',type='string',default=None,help='create inputs for xyz files containing the keyword')
   parser.add_option('-t','--target',dest='target',action='callback',callback=string_sp_callback_space,type='string',default=None,help='create input for certain xyz files')
   parser.add_option('--onsite',dest='onsite',action='store_true',default=False,help='frgm file and xyz file under the same dir and sharing the same nameroot')
   parser.add_option('-b','--basis',dest='basis',action='callback',callback=string_sp_callback, type='string', default='aug-cc-pvtz',help='The target basis (default is aug-cc-pVTZ)')
   parser.add_option('-m','--method',dest='method',action='callback',type='string', default=None, callback=string_sp_callback,help='The methods (density functionals) to use')
   parser.add_option('-i','--input_path',dest='input_path',action='store',type='string', default='input/',help='The directory storing the generated inputs')
   parser.add_option('--pop',dest='pop_scheme',action='store',type='string',default='both',help='CDFT population scheme to use [default is doing both 1 (Becke) and 5 (FBH)]')
   parser.add_option('--cdft_only', dest='cdft_only', action='store_true',default=False,help='DO CDFT only; no full SCF')
   options, args = parser.parse_args(ArgsIn)

   if not options.onsite:
      if len(args) < 4:
         parser.print_help()
         sys.exit(1)
   else:
      if len(args) < 3:
         parser.print_help()
         sys.exit(1)

   if not options.all and options.target==None and options.keyword==None:
      print("The target directory must be specified: one or some or all")
      parser.print_help()
      sys.exit(1)

   return options, args

def string_sp_callback(option, opt, value, parser):
   setattr(parser.values, option.dest, value.split(','))

def string_sp_callback_space(option, opt, value, parser):
   setattr(parser.values, option.dest, value.split(' '))

class XYZ:
   def __init__(self, xyz_file):
      #print xyz_file
      self.Name = re.search("/([^/]+).xyz$", xyz_file).group(1)
      f = open(xyz_file, 'r')
      self.AtomList = []
      self.CoordList = []
      for line in f.readlines():
         l = re.search('^\s*(\d+)\s*$', line)
         if l!=None:
            self.NAtom = int(l.group(1))
         l = re.search('(\S+)\s+(\S+)\s+(\S+)\s+(\S+)', line)
         if l!=None:
            self.AtomList.append(l.group(1))
            coord = float(l.group(2)), float(l.group(3)), float(l.group(4))
            self.CoordList.append(coord)

      if(len(self.AtomList)!=self.NAtom):
         print("Error in number of atoms")
         sys.exit(1)


def ParseFRGM(FRGMFile, debug = False):
   FRGM = {}
   counter = 0
   f = open(FRGMFile,'r')
   line = f.readline()
   while line!='':
      l=re.search("(\#)",line) 
      if (l==None):
         counter = counter + 1
         if counter == 1:
            l=re.search("(\S+)",line) 
            if (not l==None):
               FRGM["total_charge"] = int(l.group(1)) 
               if debug:
                  print("supersystem charge is "+ str(FRGM["total_charge"]))
            else:
               print("error parsing frgm file")
         if counter == 2:
            l=re.search("(\S+)",line) 
            if (not l==None):
               FRGM["total_mult"] = int(l.group(1)) 
               if debug:
                  print("supersystem multiplicity is "+ str(FRGM["total_mult"]))
            else:
               print("error parsing frgm file")
         if counter == 3:
            l=re.search("(\S+)",line) 
            if (not l==None):
               FRGM["charge_frgm"] = [int(i) for i in line.split()]
               if debug:
                  print("printing fragment charges")
                  print(FRGM["charge_frgm"])
            else:
               print("error parsing frgm file")
         if counter == 4:
            l=re.search("(\S+)",line) 
            if (not l==None):
               FRGM["mult_frgm"] = [int(i) for i in line.split()]
               if debug:
                  print("printing fragment multiplicites")
                  print(FRGM["mult_frgm"])
            else:
               print("error parsing frgm file")
         if counter == 5:
            l=re.search("(\S+)",line) 
            if (not l==None):
               FRGM["atoms_frgm"] = [int(i) for i in line.split()]
               if debug:
                  print("printing number of atoms in each fragment")
                  print(FRGM["atoms_frgm"])
            else:
               print("error parsing frgm file")
            #make a list for number of atoms prior to each fragment (offset)
            FRGM["NFrgm"] = len(FRGM["atoms_frgm"])
            FRGM["atoms_offset"] = np.zeros(FRGM["NFrgm"],dtype=int)
            offset = 0
            for index in range(0,FRGM["NFrgm"]):
               FRGM["atoms_offset"][index] = offset
               offset += FRGM["atoms_frgm"][index]
      line = f.readline()
   if counter != 5:
      print("did not parse the expected number of lines in "+FRGMFile) 
   return FRGM

def ParseRems(RemFile):
   f = open(RemFile,'r')
   REMS = {}
   REMS["name"] = RemFile[4:]
   REMS["nrems"] = 0
   currem = 0
   REMS["the_rem"] = {}
   line = f.readline()
   while line!='':
      l=re.search("(\S+)\s+(\S+)",line) #rem and value
      if (not l==None):
         REMS["the_rem"][str(currem)] = {}
         REMS["the_rem"][str(currem)]["name"] = l.group(1).upper()
         REMS["the_rem"][str(currem)]["value"] = l.group(2).upper()
         currem += 1
         REMS["nrems"] = currem
      line = f.readline()
   f.close()
   return REMS

def ModRem(r_name,r_value,MyREMS):
	#see if the rem is already set
   REM_NAME = r_name.upper()
   REM_VALUE = r_value.upper()
   done = False
   for rem in range(MyREMS["nrems"]):
      if (MyREMS["the_rem"][str(rem)]["name"] == REM_NAME):
	#found in the rem already set up
         MyREMS["the_rem"][str(rem)]["value"] = REM_VALUE
         done = True
   if (not done):	#not find, add this new rem
      currem = MyREMS["nrems"]
      MyREMS["the_rem"][str(currem)] = {}
      MyREMS["the_rem"][str(currem)]["name"] = REM_NAME
      MyREMS["the_rem"][str(currem)]["value"] = REM_VALUE
      MyREMS["nrems"] = currem + 1
   return

def AppendRem(fh,MyREMS):
   fh.write('$rem\n')
   for rem in range(MyREMS["nrems"]):
      fh.write(MyREMS["the_rem"][str(rem)]["name"]+'  '+MyREMS["the_rem"][str(rem)]["value"]+'\n')
   fh.write('$end\n')
   return

def WriteMolecule_Frgm(fw, XYZ, FRGM):
   fw.write('$molecule\n')
   #total charge and mult
   fw.write("%d %d\n" %(FRGM["total_charge"], FRGM["total_mult"]))
   #loop over fragments
   for ifrgm in range(0, FRGM["NFrgm"]):
      fw.write('--\n')
      fw.write("%d %d\n" %(FRGM["charge_frgm"][ifrgm], FRGM["mult_frgm"][ifrgm]))
      natom_frgm = FRGM["atoms_frgm"][ifrgm]
      index_start = FRGM["atoms_offset"][ifrgm]
      for iatom in range(index_start, index_start+natom_frgm):
         atomic_symbol = XYZ.AtomList[iatom]
         x, y, z = XYZ.CoordList[iatom]
         fw.write("%-4s %-10.5f %-10.5f %-10.5f\n" %(atomic_symbol, x, y, z))
   fw.write('$end\n')
   fw.write('\n')

def WriteMolecule_Read(fw):
   fw.write('$molecule\n')
   fw.write('read\n')
   fw.write('$end\n\n')

def basis_abbr(BasName):    #generating abbreviated name for basis sets, using for input file names
   fullname = BasName.lower()
   if fullname == 'cc-pvdz':
      return 'dz'
   elif fullname == 'cc-pvtz':
      return 'tz'
   elif fullname == 'cc-pvqz':
      return 'qz'
   elif fullname == 'aug-cc-pvdz':
      return 'adz'
   elif fullname == 'aug-cc-pvtz':
      return 'atz'
   elif fullname == 'aug-cc-pvqz':
      return 'aqz'
   elif fullname == 'def2-svpd' or fullname == 'svpd':
      return 'svpd'
   elif fullname == 'def2-tzvpp' or fullname == 'tzvpp':
      return 'tzvpp'
   elif fullname == 'def2-tzvppd' or fullname == 'tzvppd':
      return 'tzvppd'
   elif fullname == 'def2-qzvpp' or fullname == 'qzvpp':
      return 'qzvpp'
   elif fullname == 'def2-qzvppd' or fullname == 'qzvppd':
      return 'qzvppd'
   elif fullname == 'pc-2':
      return 'pc2'
   elif fullname == 'pc-3':
      return 'pc3'
   elif fullname == 'aug-pc-2':
      return 'apc2'
   elif fullname == 'aug-pc-3':
      return 'apc3'
   elif fullname == 'dp':
      return 'dp'
   elif fullname == 'tp':
      return 'tp' 
   elif fullname == 'lp':
      return 'lp'
   else:
      print("unrecognized basis choice")
      sys.exit(1)

def set_rems_common(curREM, method, basis):
   if basis.upper() == 'SVPD':
      ModRem('BASIS','DEF2-SVPD',curREM)
   elif basis.upper() == 'TZVPP':
      ModRem('BASIS','DEF2-TZVPP',curREM)
   elif basis.upper() == 'TZVPPD':
      ModRem('BASIS','DEF2-TZVPPD',curREM)
   elif basis.upper() == 'QZVPP':
      ModRem('BASIS','DEF2-QZVPP',curREM)
   elif basis.upper() == 'QZVPPD':
      ModRem('BASIS','DEF2-QZVPPD',curREM)
   elif basis.upper() == 'DP': #double-zeta Pople: 6-31+G(d)
      ModRem('BASIS','6-31+G(d)', curREM)
   elif basis.upper() == 'TP': #triple-zeta Pople: 6-311++G(2df,2pd)
      ModRem('BASIS','6-311++G(2df,2pd)',curREM)
   elif basis.upper() == 'LP':
      ModRem('BASIS','6-311++G(3df,3pd)', curREM)
   else: #copy the name of standard basis
      ModRem('BASIS', basis, curREM)
   ModRem('MEM_TOTAL', '8000', curREM)
   ModRem('MEM_STATIC','2000', curREM)
   ModRem('SCF_GUESS', 'FRAGMO', curREM)
   ModRem('METHOD', method, curREM)	
   if (method != 'HF'):
      ModRem ('XC_GRID', '000099000590', curREM)		
      ModRem ('NL_GRID', '1', curREM)
   #deal with -D3 in the method
   if "-D3" in method.upper():
      add_d3_tail(method, curREM)

def set_rems_cdft(curREM, pop_scheme):
   ModRem('CDFT', 'TRUE', curREM)
   ModRem('CDFT_THRESH', '7', curREM)
   ModRem('CDFT_POP_SCHEME', str(pop_scheme), curREM)
   ModRem('CDFT_BECKE_POP', 'TRUE', curREM) 

def add_d3_tail(method, curREM):
   if method.upper() == 'WB97X-D3' or method.upper() == 'B97-D3':
      return
   l = re.search('(\S+)-(D3\S*)', method)
   parent_func = l.group(1)
   tail = l.group(2)
   ModRem('METHOD', parent_func, curREM)
   if 'BJ' in tail.upper():
      ModRem('DFT_D', 'D3_BJ', curREM)
   elif 'OP' in tail.upper():
      ModRem('DFT_D', 'D3_OP', curREM)
   elif 'CSO' in tail.upper():
      ModRem('DFT_D', 'D3_CSO', curREM)
   else:
      ModRem('DFT_D', 'EMPIRICAL_GRIMME3', curREM)
   
def AppendCDFTSection(fw, FRGM):
   if FRGM["NFrgm"] > 2:
      print("Can only support jobs with two fragments for now")
      sys.exit(0)

   fw.write('\n$cdft\n')
   #let's write first fragment's charge (note: if non-zero, the sign needs to be changed)

   if FRGM["charge_frgm"][0] != 0:
      charge = -1.0*float(FRGM["charge_frgm"][0])
   else:
      charge = 0.0
   fw.write("%.1f\n" %charge)
   fw.write("1.0  1  %d\n" %FRGM["atoms_frgm"][0])
   fw.write("$end\n")


def XYZ_to_Input(fw, XYZ, FRGM, curREM, pop_scheme=-1, read_mol=False):
   #check if unrestricted (any open-shell fragment?)
   unrestricted=False
   for ifrgm in range(0, FRGM["NFrgm"]):
      if FRGM["mult_frgm"][ifrgm] > 1:
         unrestricted=True
         break
   if unrestricted:
      print("Unrestricted system not allowed yet")
      sys.exit(0)
   if not read_mol:
      WriteMolecule_Frgm(fw, XYZ, FRGM)
   else:
      WriteMolecule_Read(fw)

   AppendRem(fw, curREM)
   if pop_scheme > 0:
      AppendCDFTSection(fw, FRGM)

def XYZ_to_Input_Integrated(fw, XYZ, FRGM, method, basis, options):
   if options.pop_scheme.lower() == 'fbh':
      pop_scheme = 5
   else:
      pop_scheme = 1   #if do both, do becke first
   curREM = ParseRems('rems/rem_cdft')
   set_rems_common(curREM, method, basis)
   set_rems_cdft(curREM, pop_scheme)
   XYZ_to_Input(fw, XYZ, FRGM, curREM, pop_scheme)

   if options.pop_scheme.lower() == 'both':
      pop_scheme = 5
      #reuse the rems
      set_rems_cdft(curREM, pop_scheme)
      fw.write('\n@@@\n')
      XYZ_to_Input(fw, XYZ, FRGM, curREM, pop_scheme, True) #read_mol=true
   
   if not options.cdft_only: #standard SCF job
      pop_scheme = -1
      curREM = ParseRems('rems/rem_stdscf')
      set_rems_common(curREM, method, basis)
      fw.write('\n@@@\n')
      XYZ_to_Input(fw, XYZ, FRGM, curREM, pop_scheme, True)
      
      
#the script 
options, args = ParseInput(sys.argv)
xyz_path = args[1]
rem_file = args[2]
frgm_partition = ''
if not options.onsite:
   frgm_partition = args[3]
if xyz_path[-1:] != '/':
   xyz_path += '/'

#determine xyz_file list
curdir = os.getcwd()
xyzfile_list = []
if options.all:
   xyzfile_list = glob.glob(xyz_path+'*.xyz')
elif options.keyword:
   xyzfile_list = glob.glob(xyz_path+'*'+options.keyword+'*.xyz')
if options.target!=None:
   for xyz_file in options.target:
      if xyz_file not in xyzfile_list:
         xyzfile_list.append(xyz_file)

#check the input_path
input_path = options.input_path
if input_path[-1:] != '/':
   input_path += '/'
if not os.path.exists(input_path):
   sp.call(['mkdir', input_path])

#parse the fragment file
FRGM = ''
if not options.onsite:   #all xyz files share the common frgm file: parse it beforehand
   FRGM = ParseFRGM(frgm_partition)

#create the input file, and move it into the input_path
for method in options.method:
   for basis in options.basis: 
      for xyz_file in xyzfile_list:
         parsed_XYZ = XYZ(xyz_file)
         if options.onsite:
            frgm_file = xyz_file[:-4]+'.frgm'
            FRGM = ParseFRGM(frgm_file)
         inputfile = input_path+parsed_XYZ.Name+'_cdft_'+method+'_'+basis_abbr(basis)+'.in'
         fw = open(inputfile, 'w')
         XYZ_to_Input_Integrated(fw, parsed_XYZ, FRGM, method, basis, options)
         fw.close()
