#! /usr/bin/env python

import os, sys, re, glob
import subprocess as sp
from optparse import OptionParser

def ParseInput(ArgsIn):
   UseMsg = '''
   make_input_stark_in_silico [xyz_file] [field_min] [field_max] [input_dir]
   '''
   parser = OptionParser(usage=UseMsg)
   parser.add_option('--increment',dest='increment',type='int',action='store',default=10,help='increment of field scan (default: 10)')
   parser.add_option('--sol',dest='sol',type='string',action='store',default=None,help='doing PCM; specify the relevant input section')
   parser.add_option('--noopt',dest='noopt',action='store_true',default=False,help='skip the geometry optimization before frequency calculation')
   options, args = parser.parse_args(ArgsIn)
   if len(args) < 5:
      parser.print_help()
      sys.exit(0)
   return options, args

options, args = ParseInput(sys.argv)
xyz_file = args[1]
field_min = int(args[2])
field_max = int(args[3])
input_dir = args[4]
increment = options.increment

for field in range(field_min, field_max+1, increment):
   if options.noopt:
      command = "make_input_sp_geom --freq"
   else:
      command = "make_input_sp_geom --opt_freq"
   command += " --tight -t " + xyz_file + " -m B3LYP -b 6-31+gdp -i " + input_dir + " --dipole_field=" + str(field)
   if options.sol != None:
      command += ' --sol=PCM --sol_file='+options.sol
   print (command)
   os.system(command)

