#! /usr/bin/env python3

import os, sys, glob, re
import subprocess as sp
import numpy as np
from optparse import OptionParser

def ParseInput(ArgsIn):
   UseMsg = "parse_delta_scf [options] [outfile]"
   parser = OptionParser(usage=UseMsg)
   
   options, args = parser.parse_args(ArgsIn)
   if len(args) < 2:
      parser.print_help()
      sys.exit(0)
   return options, args

def parse_deltascf_energy_single_file(outfile):
   Ha_to_eV = 27.2114
   out = sp.check_output(["grep", "ion met", outfile])
   gs_energy = float(out.split()[1])
   ex_energy = float(out.split()[-5])
   return Ha_to_eV * (ex_energy - gs_energy)

options, args = ParseInput(sys.argv)
outfile = args[1]
print ("Delta SCF excitation energy: %.4f eV" %parse_deltascf_energy_single_file(outfile))
