#! /usr/bin/env python

import re, os, sys, glob

if len(sys.argv) < 3:
   print "Usage: replace [old_pattern] [new_pattern]"
   sys.exit(1)

old = sys.argv[1]
new = sys.argv[2]
print "replacing %s with %s in all filenames" %(old, new)
replace_list = glob.glob('*'+old+'*')
for oldfile in replace_list:
    l = re.search('(\S+)'+old+'(\S+)', oldfile)
    newfile = l.group(1) + new + l.group(2)
    command = 'mv ' + oldfile + ' ' + newfile
    print command
    os.system(command)
