#! /usr/bin/env python

import os, glob, sys, re
import subprocess as sp
from optparse import OptionParser

def ParseInput(ArgsIn):
   UseMsg = "%prog [options] [input_dir]"
   parser = OptionParser(UseMsg)
   #parser.add_option('-Q', '--qchem', dest='qchem', action='store', default=None, type='string', help='specify the requested bashrc')
   parser.add_option('-n', '--nthreads', dest='nthread', action='store', default=8, type='int', help='number of threads')
   options, args = parser.parse_args(ArgsIn)
   if len(args) < 2:
      print "Specify the input directory"
      parser.print_help()
      sys.exit(0)

   return options,args
  
options, args = ParseInput(sys.argv)
#if options.qchem!=None:
#   command = "source "+options.qchem
#   print(command)
#   sp.call(["source", "~/.bashrc_genscf"])
#   #os.system("echo $QC")
#   sys.exit(0)

curdir = os.getcwd()
input_dir = args[1]
os.chdir(input_dir)
inputfile_list = glob.glob('*.in')
for inputfile in inputfile_list:
   outfile = inputfile[:-2]+'out'
   sp.call(['qchem', '-nt', str(options.nthread), inputfile, outfile])
os.chdir(curdir)
