#!/usr/bin/env python

import os, glob, re, sys
import subprocess as sp
from optparse import OptionParser

def ParseInput(ArgsIn):
   UseMsg = '''
   python runjobs_parallel [options] [input_dir]
   '''
   parser = OptionParser(usage=UseMsg)
   parser.add_option('-n', '--ncores', dest='ncores', type='int', action='store', default=4, help='Number of threads to run the jobs')
   parser.add_option('-k', '--keyword', dest='keywords', type='string', action='callback', callback=string_sp_callback, default=None,help='only run jobs that contain the given keywords')
   parser.add_option('-u', '--union', dest='union', action='store_true', default=False, help='run the union of jobs that contain the keywords (the default will take the intersection)')
   parser.add_option('-q', '--queue', dest='queue', action='store', default=None, help='specify the queue you are going to run these jobs')
   parser.add_option('-c','--cluster',dest='cluster',type='str',default='haswell',help="Specifies the specific cluster (haswell, knl) to use")
   parser.add_option('-v', '--reverse',dest='reverse',type='string',action='callback',callback=string_sp_callback,default=None,help='Not running jobs containing these keywords')
   parser.add_option('-s', '--software', dest='software', type='str', action='store',default='qchem',help='specify the software to run\nCurrently supported: qchem')
   parser.add_option('--ppn',dest='ppn',action='store',type=int,default=None,help='ppn')
   parser.add_option('--env',dest='env',type='str',default=None,help="Specifies a file to source before running")
   parser.add_option('--bigmem',dest='bigmem',action='store_true',default=False,help='use the submitSLURM_bibmem script')
   parser.add_option('--time',dest='time',type='string',action='store',default='48:00:00',help='wall time (default: 48h)')
   options,args = parser.parse_args(ArgsIn)
   if len(args) < 2:
      print "Specify the input diretory"
      parser.print_help()
      sys.exit(0)

   return options,args

def string_sp_callback(option, opt, value, parser):
   setattr(parser.values, option.dest, value.split(','))

def reverse_screening(jobname, options):
   if options.reverse != None:
      for rev_key in options.reverse:
         if rev_key in jobname:
            return False
   return True

def Determine_joblist(options, args):
   joblist = [] 
   input_dir = args[1]
   curdir = os.getcwd()
   os.chdir(input_dir)
   if options.keywords == None:
      print "Run all the jobs under the input dir"
      temp_list = glob.glob('*.in')
      for temp in temp_list:
         if reverse_screening(temp, options):
            joblist.append(temp)

   elif not options.union:
      print "Figure out the overlap of all the keywords" 
      keyword_list = options.keywords
      print keyword_list
      temp_list = []
      temp_list = glob.glob('*'+keyword_list[0]+'*.in')
      #subtractive approach
      for temp in temp_list:
         remove = False
         for keyword in keyword_list:
            if keyword not in temp:
               remove = True
               break
         if reverse_screening(temp, options):
            joblist.append(temp)

   elif options.union:
      print "Figure out the union of all the keywords"
      keyword_list = options.keywords
      print keyword_list
      #additive approach
      for keyword in keyword_list:
         temp_list = glob.glob('*'+keyword+'*.in')
         for temp in temp_list:
            if temp not in joblist and reverse_screening(temp, options):
               joblist.append(temp)
   os.chdir(curdir)
   print "%d jobs" %len(joblist)
   print joblist 
   return joblist

def run_jobs(joblist, options, args):
   input_dir = args[1]
   curdir = os.getcwd()
   os.chdir(input_dir)
   ncores = options.ncores

   if options.bigmem:
      command = "submitSLURM_bigmem -t openmp -p "+str(ncores)+' -s qchem'
   else:
      command = "submitSLURM -t openmp -p "+str(ncores)+' -s qchem'
   if options.queue != None:
      command += ' -q '+options.queue
   if options.cluster != None and not options.bigmem:
      command += ' -a '+options.cluster
   if options.time != None:
      command += ' -l time='+options.time
   if options.ppn != None:
      command += ' --ppn='+str(options.ppn)
   if options.env != None:
      command += ' --env '+options.env
   for jobname in joblist:
      submit_command = command+' '+jobname
      #print submit_command
      os.system(submit_command)

   os.chdir(curdir)



#the script
options, args = ParseInput(sys.argv)
joblist = Determine_joblist(options,args)
run_jobs(joblist, options,args)
