#!/usr/bin/env python

import os, glob, re, sys
import subprocess as sp
from optparse import OptionParser

def ParseInput(ArgsIn):
   UseMsg = '''
   sort_output [options] [output_dir]
   '''
   parser = OptionParser(usage=UseMsg)
   parser.add_option('-k', '--key', dest='keywords', type='string', action='callback', callback=string_sp_callback, default=None, help='keywords used to sort output files (also as subdirectory names)')

   options,args = parser.parse_args(ArgsIn)
   if len(args) < 2:
      print "Specify the output directory"
      parser.print_help()
      sys.exit(0)

   return options,args


def string_sp_callback(option, opt, value, parser):
   setattr(parser.values, option.dest, value.split(','))


options, args = ParseInput(sys.argv)
outdir = args[1]
curdir = os.getcwd()
os.chdir(outdir)
for keyword in options.keywords:
   if not os.path.exists(keyword):
      sp.call(['mkdir', keyword])
   os.system('mv *_'+keyword+'_*.out '+keyword)

os.chdir(curdir)    
